279 voting power is not synced properly on start of epoch
Hydra-Chain/hydragon-node pull request #76
Opened 2024-11-12 16:48 UTC by Vitomir2

# Description

- use epoch.Validators.Copy() in order to ensure that the validators are not passed by reference and updated in some of the next functions;
- optimize if conditions for the end and start of epoch;
- get the validators from the last epoch;
- update the implementation for the generation of the syncValidatorsData input to properly extract the removed validators, too;
- add tests;

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

I have configured the blockchain locally and have tested if the syncValidatorsData's input is generated correctly and it seems all work fine. Additionally, added some tests to ensure that the extract function works properly.

2024-11-13 13:50 UTC, R-Santev requested changes

2024-11-13 13:50 UTC, R-Santev commented on consensus/polybft/consensus_runtime_test.go
> +	expectedUpdatedValidatorsPower := extractUpdatedValidatorsVotingPower(validatorsDelta, valSetAccounts, accSet)
instead of using additional function, can't you hardcode the expectedUpdatedValidatorsPower

2024-11-13 13:50 UTC, R-Santev commented on consensus/polybft/consensus_runtime_test.go
> +func TestConsensusRuntime_generateSyncValidatorsDataTxInputRemoved(t *testing.T) {
maybe better having a combined test where there are added updated and deleted validators

2024-11-14 09:55 UTC, Vitomir2 commented on consensus/polybft/validator/validator_metadata.go
> +	if validatorsDelta.Added.Len() > 0 || validatorsDelta.Updated.Len() > 0 {
Yeah, it will be better to do it like that. For some reason, I was confused that I am missing the `votingPower` in the validatorSetDelta.

2024-11-15 07:06 UTC, R-Santev approved these changes

2024-11-15 08:36 UTC, merged